org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[4,)

mod_id=vulkanchunk
mod_name=Vulkan Chunk
mod_license=MIT
mod_version=0.1.0
mod_group_id=dev.vulkanchunk

lwjgl_version=3.3.3
